plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/chris/Documents/營運業務/業績分析系統"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]